# Generated by Django 5.2.8 on 2025-11-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120)),
                ('definition', models.TextField(blank=True)),
                ('synonyms', models.TextField(blank=True)),
                ('antonyms', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
